### ISSUE TITLE
getting some errors when trying to run tic tac toe

### ISSUE THREAD

**Issue by wabi69sabi** [noobieruby/Python#1]
maybe your readme is missing the requirements to run these scripts (python version, libraries to install...?)

I cloned this folder and got the following errors:

when running tictactoe.py
```
File "tictactoe.py", line 109, in <module>
input('                     ********************************* \n                     *                               *\n                     *                               *\n                     *    Welcome to Tic Tac Toe!    *\n                     *                               *\n                     *                               *\n                     *********************************\n\n\n\n\n\n\n\n\npress Enter to conintue....')
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

when running tictactoe:

```
Traceback (most recent call last):
  File "tictactoe", line 1, in <module>
    from IPython.display import clear_output
ImportError: No module named IPython.display
```

**Comment by wabi69sabi** [comment]
Ok, I got it to work by using python 3.0, which is something that should be added to the README.md

There were also some wrong results, check out the result:
```
     |     |
  O  |  O  |  X
     |     |
-----------------
     |     |
  O  |  X  |  O
     |     |
-----------------
     |     |
  X  |  O  |  X
     |     |



This game was a tie! Good Job!
Would you like to play again? (yes or no):
```

**Comment by wabi69sabi** [comment]
I noticed your check in line 40 which shoulda caught this as a win, but for some reason was either not triggered or failed for some reason
